version: "3.7"
services:
  api:
    build: ./
    command: ['npm', 'run', 'start:dev']
    container_name: hackathon
    environment:
      - LOG_LEVEL=debug
      - CACHE_GRAPHQL_PARSE=true
      - CACHE_GRAPHQL_RESPONSE=true
      - CACHE_GRAPHQL_VALIDATION=true
    image: hackathon
    networks:
      - hackathon
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/var/node
networks:
  hackathon:
