version: '3.7'
services:
  api: &base_application
    build: ./
    container_name: hackathon
    environment:
      - LOG_LEVEL=debug
      - APP_USE_ENVELOP=true
      - CACHE_GRAPHQL_PARSE=true
      - CACHE_GRAPHQL_RESPONSE=true
      - CACHE_GRAPHQL_VALIDATION=true
      - DB_HOST=database
      - DB_SCHEMA=hackathon
    image: hackathon
    networks:
      - hackathon
    ports:
      - 3000:3000

  api-dev:
    << : *base_application
    command: ['npm', 'run', 'start:dev']
    container_name: hackathon-dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/var/node

  database:
    container_name: hackathon-database
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=hackathon
    image: mariadb:10.6.4
    networks:
      - hackathon
    ports:
      - 3306:3306/tcp
    volumes:
      - mariadb-data:/var/lib/mysql

networks:
  hackathon:

volumes:
  mariadb-data: