version: "3.7"
services:
  api:
    build: ./
    command: ['npm', 'run', 'start:dev']
    container_name: hackathon
    environment:
      - LOG_LEVEL=debug
    image: hackathon
    networks:
      - hackathon
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./lib:/var/node/lib
      - ./server:/var/node/server
networks:
  hackathon:
